import './AIAnswerCard.css'

const imgIntersect = "https://www.figma.com/api/mcp/asset/e63ccd2a-a9fe-4a21-9b39-e7f1fdf98980";
const imgIntersect1 = "https://www.figma.com/api/mcp/asset/33557879-60a2-415f-89bb-a794c98b8c2a";
const imgIntersect2 = "https://www.figma.com/api/mcp/asset/5bb74811-c26d-43df-a5fb-38df5d00c356";
const imgIntersect3 = "https://www.figma.com/api/mcp/asset/d2771c6a-711b-48d1-b579-c8b6956eed68";
const imgEllipse297 = "https://www.figma.com/api/mcp/asset/48a5b59e-a1a3-4684-8733-c738a11997b9";
const imgEllipse300 = "https://www.figma.com/api/mcp/asset/ccc28920-84ae-40dd-8f49-18803f9e88f5";
const imgEllipse304 = "https://www.figma.com/api/mcp/asset/6db54db8-ac36-4cc9-9179-ddfaa8502e64";
const imgEllipse305 = "https://www.figma.com/api/mcp/asset/e186481a-934b-43d8-812f-dcd0fe0b2387";
const imgVector1 = "https://www.figma.com/api/mcp/asset/b3276a5e-a9ed-4745-9d2b-4fbaf2376960";
const imgVector2 = "https://www.figma.com/api/mcp/asset/b0a0554e-024d-44eb-98b1-7bb4112a1cc2";

function SlackbotIcon() {
  return (
    <div className="slackbot-icon">
      <div className="slackbot-icon__bg" />
      <img src={imgIntersect} alt="" className="slackbot-icon__q slackbot-icon__q--br" />
      <img src={imgIntersect1} alt="" className="slackbot-icon__q slackbot-icon__q--tr" />
      <img src={imgIntersect2} alt="" className="slackbot-icon__q slackbot-icon__q--bl" />
      <img src={imgIntersect3} alt="" className="slackbot-icon__q slackbot-icon__q--tl" />
      {/* Left eyebrow */}
      <div className="slackbot-face__brow slackbot-face__brow--l">
        <img src={imgEllipse297} alt="" />
      </div>
      {/* Right eyebrow */}
      <div className="slackbot-face__brow slackbot-face__brow--r">
        <img src={imgEllipse300} alt="" />
      </div>
      {/* Left eye */}
      <div className="slackbot-face__eye slackbot-face__eye--l">
        <img src={imgEllipse304} alt="" />
      </div>
      <div className="slackbot-face__pupil slackbot-face__pupil--l">
        <img src={imgEllipse305} alt="" />
      </div>
      {/* Right eye */}
      <div className="slackbot-face__eye slackbot-face__eye--r">
        <img src={imgEllipse304} alt="" />
      </div>
      <div className="slackbot-face__pupil slackbot-face__pupil--r">
        <img src={imgEllipse305} alt="" />
      </div>
      {/* Mouth */}
      <div className="slackbot-face__mouth">
        <img src={imgVector1} alt="" />
      </div>
      <div className="slackbot-face__smile">
        <img src={imgVector2} alt="" />
      </div>
    </div>
  )
}

interface AIAnswerCardProps {
  onClick?: () => void
}

export default function AIAnswerCard({ onClick }: AIAnswerCardProps) {
  return (
    <div className="ai-card" onClick={onClick} style={onClick ? { cursor: 'pointer' } : undefined}>
      <div className="ai-card__header">
        <SlackbotIcon />
        <span className="ai-card__title">AI answer</span>
      </div>

      <div className="ai-card__divider" />

      <div className="ai-card__body">
        <div className="ai-card__text">
          <p>
            Based on recent messages in your workspace, the latest search strategy is the Agentic Search Prototype, documented by{' '}
            <a href="#" className="ai-card__mention">@Markee Smith</a>{' '}
            on March 23rd.
          </p>
          <p>Here's the key approach:</p>
          <p>
            <strong>Architecture</strong><br />
            The new strategy uses a search subagent that handles multi-step retrieval and synthesis internally, decoupled from Slackbot's orchestration layer. This solves three main problems:
          </p>
          <ul>
            <li>Context window inflation from raw search results</li>
            <li>Lack of modularity in search logic</li>
            <li>Limited observability into search performance metrics</li>
          </ul>
          <p>
            Three-Tier Depth System<br />
            The strategy classifies searches into three depths:
          </p>
          <ol>
            <li>QUICK - Single-query plan with direct Solr search (no LLM call)</li>
            <li>STANDARD - Multi-query plan generated by Haiku for broader coverage</li>
            <li>DEEP - Advanced multi-step retrieval for complex research queries</li>
          </ol>
        </div>
      </div>

      <div className="ai-card__fade" />
      <a href="#" className="ai-card__readmore">Read more</a>
    </div>
  )
}
